load("@rules_wasm//wasm:defs.bzl", "wit_package")

package(default_visibility = ["//visibility:public"])

wit_package(
    name = "grpc",
    srcs = ["grpc.wit"],
    package = "vimana:grpc",
)

# Gather all the packages (transitively)
# that a generated WIT server package needs in the `deps/` folder.
wit_package(
    name = "deps",
    package = "vimana",
    deps = [
        ":grpc",
        "@rules_wasm//wasip2:clocks",
        "@rules_wasm//wasip2:http",
        "@rules_wasm//wasip2:random",
    ],
)
