load("@rules_wasm//wasm:defs.bzl", "wit_package")

package(default_visibility = ["//visibility:public"])

wit_package(
    name = "grpc",
    srcs = ["grpc.wit"],
    package = "vimana:grpc",
)

# Gather all the packages (transitively)
# that a generated WIT server package needs in the `deps/` folder.
wit_package(
    name = "deps",
    package = "vimana",
    deps = [
        ":grpc",
        # The complete WASI API is made available to guest components.
        # However, certain APIs, like the filesystem API, are essentially useless
        # due the purposefully-restricted access implemented by the runtime.
        "@rules_wasm//wasip2:cli",
        "@rules_wasm//wasip2:clocks",
        "@rules_wasm//wasip2:filesystem",
        "@rules_wasm//wasip2:http",
        "@rules_wasm//wasip2:io",
        "@rules_wasm//wasip2:random",
        "@rules_wasm//wasip2:sockets",
    ],
)
