load("//operator:directory.bzl", "collect_directory", "source_files_except_build_and_templates")

collect_directory(
    name = "scorecard",
    srcs = source_files_except_build_and_templates() + [
        "//operator/config/scorecard/bases",
        "//operator/config/scorecard/patches",
    ],
    visibility = ["//operator/config:__pkg__"],
)
