load("@grpc//bazel:python_rules.bzl", "py_grpc_library", "py_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_wasm//c:defs.bzl", "c_component")
load("//compiler:defs.bzl", "vimana_protoc")

package(
    default_visibility = [
        "//cluster/tests:__pkg__",
        "//runtime/tests:__pkg__",
    ],
)

c_component(
    name = "mvp",
    srcs = ["mvp.c"],
    wit = ":mvp-vimana",
    world = "server",
)

vimana_protoc(
    name = "mvp-vimana",
    package = "foo",
    proto = ":mvp-proto",
)

proto_library(
    name = "mvp-proto",
    srcs = ["mvp.proto"],
)

py_proto_library(
    name = "mvp-py-pb2",
    deps = [":mvp-proto"],
)

py_grpc_library(
    name = "mvp-py-grpc",
    srcs = [":mvp-proto"],
    deps = ["mvp-py-pb2"],
)
