load("@grpc//bazel:python_rules.bzl", "py_grpc_library", "py_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_wasm//c:defs.bzl", "c_component")
load("@rules_wasm//go:defs.bzl", "go_component")
load("@rules_wasm//rust:defs.bzl", "rust_component")
load("//compiler:defs.bzl", "vimana_protoc")

package(
    default_visibility = [
        "//cluster/tests:__pkg__",
        "//runtime/tests:__pkg__",
    ],
)

c_component(
    name = "mvp",
    srcs = ["mvp.c"],
    wit = ":mvp-vimana",
    world = "server",
)

vimana_protoc(
    name = "mvp-vimana",
    package = "foo",
    proto = ":mvp-proto",
)

proto_library(
    name = "mvp-proto",
    srcs = ["mvp.proto"],
)

py_proto_library(
    name = "mvp-py-pb2",
    deps = [":mvp-proto"],
)

py_grpc_library(
    name = "mvp-py-grpc",
    srcs = [":mvp-proto"],
    deps = ["mvp-py-pb2"],
)

rust_component(
    name = "wasi",
    srcs = ["wasi.rs"],
    wit = ":wasi-vimana",
    world = "server",
    deps = ["@crates//:url"],
)

vimana_protoc(
    name = "wasi-vimana",
    package = "bar",
    proto = ":wasi-proto",
)

proto_library(
    name = "wasi-proto",
    srcs = ["wasi.proto"],
)

py_proto_library(
    name = "wasi-py-pb2",
    deps = [":wasi-proto"],
)

py_grpc_library(
    name = "wasi-py-grpc",
    srcs = [":wasi-proto"],
    deps = ["wasi-py-pb2"],
)

go_component(
    name = "json",
    srcs = ["json.go"],
    wit = ":json-vimana",
    wit_module = "bar/proto/server",
    world = "server",
)

vimana_protoc(
    name = "json-vimana",
    package = "bar",
    proto = ":json-proto",
)

proto_library(
    name = "json-proto",
    srcs = ["json.proto"],
    deps = ["@googleapis//google/api:annotations_proto"],
)
