// Verify various properties about the WASI implementation.

syntax = "proto3";

package bar;

// This test exercises the various capabilities of WASI
// made available to guest components.
// Typically, each method accepts an input
// and returns a pass/fail response
// depending on whether the WASI API functions as expected for that input.
service WasiExercise {
  // Components should *not* have filesystem access.
  // The test passes if opening the file at the given path fails
  // and trying to create the file at the given path also fails.
  rpc AssertNoFilesystem(StringRequest) returns (ResultResponse) {}

  // Components should have internet access.
  // The test passes if GET-requesting the given URL
  // returns a successful response.
  rpc AssertInternetAccess(StringRequest) returns (ResultResponse) {}

  // Components should have clock access.
  // The test passes if the current UNIX time in the componentj
  // is within 3 seconds of the given UNIX time.
  rpc AssertClockAccess(U64Request) returns (ResultResponse) {}
}

message ResultResponse {
  // Whether the test case was successful.
  bool passed = 1;
  // If the test case failed, this is the reason why.
  string reason = 2;
}

message StringRequest { string input = 1; }

message U64Request { uint64 input = 1; }
