load("//operator:directory.bzl", "collect_directory", "source_files_except_build_and_templates")

collect_directory(
    name = "config",
    srcs = source_files_except_build_and_templates() + [
        "//operator/config/crd",
        "//operator/config/default",
        "//operator/config/manager",
        "//operator/config/manifests",
        "//operator/config/network-policy",
        "//operator/config/prometheus",
        "//operator/config/rbac",
        "//operator/config/samples",
        "//operator/config/scorecard",
    ],
    visibility = ["//operator:__pkg__"],
)
