load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "io",
    srcs = [
        "error.rs",
        "lib.rs",
        "streams.rs",
    ],
    visibility = ["//runtime/host/wasi:__pkg__"],
    deps = [
        "//runtime/host:provide",
        "@crates//:anyhow",
        "@crates//:wasmtime",
    ],
)
