load("@bazel_skylib//rules:common_settings.bzl", "repeatable_string_flag", "string_flag")
load("@environment//:environment.bzl", "localhost")
load("@rules_python//python:defs.bzl", "py_library")
load("@rules_python//python:py_binary.bzl", "py_binary")
load("//dev/rules:delegating-string-flag.bzl", "delegating_string_flag")
load("//dev/rules:sprig.bzl", "expand_sprig")
load(":test-e2e.bzl", "component", "domain", "e2e_test", "server")

e2e_test(
    name = "mvp-test",
    domains = {
        "00000000000000000000000000000001": domain(
            aliases = ["mvp.test"],
            servers = {
                "the-mvp-server": server(
                    versions = {
                        "1.0.0": component(
                            metadata = "//cluster/tests/components:mvp-vimana",
                            implementation = "//cluster/tests/components:mvp",
                        ),
                    },
                ),
            },
        ),
    },
    executable = ":mvp",
    gateway = "the-vimana-gateway",
    resources = [":mvp.yaml"],
)

py_binary(
    name = "mvp",
    srcs = ["mvp-test.py"],
    main = "mvp-test.py",
    deps = [
        ":util",
        "//cluster/tests/components:mvp-py-grpc",
        "//cluster/tests/components:mvp-py-pb2",
        "@rules_python//python/runfiles",
    ],
)

expand_sprig(
    name = "mvp.yaml",
    dot = {"RegistryCluster": "$(REGISTRY_CLUSTER)"},
    template = "mvp.yaml.tmpl",
    toolchains = [":registry-cluster"],
)

e2e_test(
    name = "wasi-test",
    domains = {
        "00000000000000000000000000000001": domain(
            aliases = ["wasi.test"],
            servers = {
                "wasi-server": server(
                    versions = {
                        "1.2.3": component(
                            metadata = "//cluster/tests/components:wasi-vimana",
                            implementation = "//cluster/tests/components:wasi",
                        ),
                    },
                ),
            },
        ),
    },
    executable = ":wasi",
    gateway = "the-vimana-gateway",
    resources = [":wasi.yaml"],
)

py_binary(
    name = "wasi",
    srcs = ["wasi-test.py"],
    main = "wasi-test.py",
    deps = [
        ":util",
        "//cluster/tests/components:wasi-py-grpc",
        "//cluster/tests/components:wasi-py-pb2",
        "@rules_python//python/runfiles",
    ],
)

expand_sprig(
    name = "wasi.yaml",
    dot = {"RegistryCluster": "$(REGISTRY_CLUSTER)"},
    template = "wasi.yaml.tmpl",
    toolchains = [":registry-cluster"],
)

e2e_test(
    name = "json-test",
    domains = {
        "00000000000000000000000000000001": domain(
            aliases = ["json.test"],
            servers = {
                "json-server": server(
                    versions = {
                        "1.0.0-alpha": component(
                            metadata = "//cluster/tests/components:json-vimana",
                            implementation = "//cluster/tests/components:json",
                        ),
                    },
                ),
            },
        ),
    },
    executable = ":json",
    gateway = "the-vimana-gateway",
    resources = [":json.yaml"],
    superdomain = "app.test",
)

py_binary(
    name = "json",
    srcs = ["json-test.py"],
    main = "json-test.py",
    deps = [
        ":util",
        "@pypi//requests",
        "@rules_python//python/runfiles",
    ],
)

expand_sprig(
    name = "json.yaml",
    dot = {
        "RegistryCluster": "$(REGISTRY_CLUSTER)",
        "ProtoDescriptorPath": "$(location //cluster/tests/components:json-proto)",
    },
    template = "json.yaml.tmpl",
    toolchains = [":registry-cluster"],
    deps = ["//cluster/tests/components:json-proto"],
)

py_library(
    name = "util",
    srcs = ["util.py"],
    deps = [
        "@pypi//grpcio",
        "@pypi//kubernetes",
    ],
)

# The registry to use for Vimana Wasm component "containers".
#
# Bootstrapped components will be pushed to this registry from the host machine
# before starting the test.
# During testing, nodes in the cluster will pull from (and possibly push to)
# this registry as well.
#
# If nodes in the cluster should use a different registry URI than the local machine,
# set `registry-host` and `registry-cluster` individually.
string_flag(
    name = "registry",
    build_setting_default = "",
)

registry_host_default = "{}:5000".format(localhost)

registry_cluster_default = "host.docker.internal:5000"

# The base for the URLs of all the images that are pushed prior to running E2E tests.
# The machine executing the test must be able to push to this registry.
# Do *not* include the scheme.
# `https` is assumed unless the domain is listed under `registries-insecure`.
delegating_string_flag(
    name = "registry-host",
    build_setting_default = registry_host_default,
    delegate = ":registry",
    make_variable = "REGISTRY_HOST",
)

# The base for the name of all the images that are pulled into the cluster.
# The cluster under test must be able to pull from this registry.
# Do *not* include the scheme.
# `https` is assumed unless the domain is configured as an "insecure registry" with the runtime.
delegating_string_flag(
    name = "registry-cluster",
    build_setting_default = registry_cluster_default,
    delegate = ":registry",
    make_variable = "REGISTRY_CLUSTER",
)

# The set of registry domains for which to use cleartext HTTP instead of HTTPS.
# This setting only affects `registry-host`.
repeatable_string_flag(
    name = "registries-insecure",
    build_setting_default = [registry_host_default],
)
