module(name = "vimana")

bazel_dep(name = "buildifier_prebuilt", version = "8.2.1.2", dev_dependency = True, repo_name = "buildtools")

bazel_dep(name = "bazel_skylib", version = "1.9.0")
single_version_override(
    module_name = "bazel_skylib",
    # TODO: Delete this patch once functionality is upstreamed.
    #   https://github.com/bazelbuild/bazel-skylib/issues/442
    patches = ["//dev/patches:skylib-expand-template-make-variables.patch"],
)

bazel_dep(name = "gazelle", version = "0.47.0")
bazel_dep(name = "googleapis", version = "0.0.0-20260130-c0fcb356")
bazel_dep(name = "googleapis-go", version = "1.0.0")
bazel_dep(name = "grpc", version = "1.76.0.bcr.1")
bazel_dep(name = "hermetic_cc_toolchain", version = "4.1.0")
bazel_dep(name = "jq.bzl", version = "0.6.0")
bazel_dep(name = "openssl", version = "3.5.5.bcr.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "protobuf", version = "33.5")
single_version_override(
    module_name = "protobuf",
    patches = [
        # TODO: Delete this patch once visibility is fixed.
        #   https://github.com/protocolbuffers/protobuf/pull/24895
        "//dev/patches:protobuf-conformance-visibility.patch",
        # TODO: Delete this patch once conformance is loadable.
        #   https://github.com/protocolbuffers/protobuf/pull/24487
        "//dev/patches:protobuf-conformance-delete-ruby.patch",
    ],
)

bazel_dep(name = "rules_go", version = "0.59.0")
bazel_dep(name = "rules_nodejs", version = "6.7.3")
bazel_dep(name = "rules_oci", version = "2.2.7")
single_version_override(
    module_name = "rules_oci",
    # TODO: Remove this patch once `rules_oci` moves past 2.2.7.
    #   https://github.com/bazel-contrib/rules_oci/pull/868
    patches = ["//dev/patches:rules-oci-implicit-mediatype.patch"],
)

bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_python", version = "1.8.3")
bazel_dep(name = "rules_rust", version = "0.68.1")
bazel_dep(name = "rules_rust_prost", version = "0.68.1")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "rules_wasm", version = "2.1.1")
bazel_dep(name = "cri-api")
git_override(
    module_name = "cri-api",
    commit = "c133bdabf253886f640d764d1748aa9ac644ab1c",
    remote = "https://github.com/vimana-cloud/cri-api.git",
)

bazel_dep(name = "rules_k8s")
git_override(
    module_name = "rules_k8s",
    commit = "048baf4296831413ad145977b9b6fd527724d517",
    remote = "https://github.com/vimana-cloud/rules_k8s.git",
)

environment = use_extension("//dev/rules:environment.bzl", "environment")
use_repo(environment, "environment")

# Toolchains

jq = use_extension("@jq.bzl//jq:extensions.bzl", "toolchains")
use_repo(jq, "jq_toolchains")

register_toolchains("@jq_toolchains//:all")

include("//dev:rust-cc-toolchains.MODULE.bazel")

# Rust setup:

# Register Prost Protobuf toolchain.
register_toolchains("//:protoc-rust-toolchain")

crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = ["//:Cargo.toml"],
    # Hardcode all supported Rust toolchains to make Cargo splicing more efficient.
    # https://github.com/bazelbuild/rules_rust/discussions/2259
    supported_platform_triples = [
        "aarch64-unknown-linux-gnu",
        "aarch64-apple-darwin",
        "wasm32-wasip2",
        "x86_64-unknown-linux-gnu",
        "x86_64-apple-darwin",
    ],
)

# Generate certain binaries needed for building.
crate.annotation(
    crate = "protoc-gen-prost",
    gen_binaries = ["protoc-gen-prost"],
)
crate.annotation(
    crate = "protoc-gen-tonic",
    gen_binaries = ["protoc-gen-tonic"],
)
use_repo(crate, "crates")

# Go setup:

# Use a Go toolchain satisfying the SDK version specified in `go.mod`.
go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(
    name = "go_sdk",
    version = "1.25.6",
)
go_sdk.from_file(go_mod = "//:go.mod")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")

# Gazelle struggles with this dependency for some reason.
# It generates a `go_proto_library` rule that only uses the gRPC compiler,
# when it needs to use both the gRPC and regular Protobuf compilers.
go_deps.module_override(
    patches = ["//dev/patches:konnectivity-client.patch"],
    path = "sigs.k8s.io/apiserver-network-proxy/konnectivity-client",
)

# Gazelle also struggles with this one, due to a conflict with the `cel-spec` Bzlmod dependency,
# which is pulled in transitively via `grpc`.
# https://github.com/google/cel-go/issues/1184
go_deps.gazelle_override(
    build_file_generation = "off",
    path = "cel.dev/expr",
)
use_repo(
    go_deps,
    "com_github_envoyproxy_gateway",
    "com_github_masterminds_sprig_v3",
    "com_github_onsi_ginkgo_v2",
    "com_github_onsi_gomega",
    "io_k8s_api",
    "io_k8s_apiextensions_apiserver",
    "io_k8s_apimachinery",
    "io_k8s_client_go",
    "io_k8s_sigs_controller_runtime",
    "io_k8s_sigs_gateway_api",
    "io_k8s_utils",
)

# Build Google API interfaces for Go.
switched_rules = use_extension("@googleapis//:extensions.bzl", "switched_rules")
switched_rules.use_languages(go = True)
use_repo(switched_rules, "com_google_googleapis_imports")

# Python setup:

# https://www.python.org/downloads/
python_version = "3.13"

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = python_version,
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = python_version,
    requirements_lock = "requirements.txt.lock",
)
use_repo(pip, "pypi")

# Docker setup

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# Distroless base for the operator image.
# https://console.cloud.google.com/artifacts/docker/distroless/us/gcr.io/static
oci.pull(
    name = "distroless-static",
    digest = "sha256:2b7c93f6d6648c11f0e80a48558c8f77885eb0445213b8e69a6a0d7c89fc6ae4",
    image = "gcr.io/distroless/static",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
)

# Node image for local E2E testing using Kind.
# https://hub.docker.com/r/kindest/node/
oci.pull(
    name = "kind-node",
    # Must match the recommended image for the release of `kind` being used.
    # https://github.com/kubernetes-sigs/kind/releases
    digest = "sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f",
    image = "docker.io/kindest/node",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
use_repo(
    oci,
    "distroless-static",
    "distroless-static_linux_amd64",
    "distroless-static_linux_arm64_v8",
    "kind-node",
    "kind-node_linux_amd64",
    "kind-node_linux_arm64",
)

# NodeJS setup (for serving documentation with VitePress):

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain()
use_repo(node, "nodejs")
