load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "encode",
    srcs = [
        "compound.rs",
        "lib.rs",
        "scalar.rs",
    ],
    visibility = [
        "//compiler/tests:__pkg__",
        "//runtime:__subpackages__",
    ],
    deps = [
        "//runtime:metadata-prost",
        "//runtime:names",
        "@crates//:anyhow",
        "@crates//:prost",
        "@crates//:tonic",
        "@crates//:wasmtime",
    ],
)
