load("@buildtools//:rules.bzl", "buildifier")

# Format all Bazel files.
buildifier(
    name = "buildifier",
    exclude_patterns = [
        "./.git/*",
    ],
    lint_mode = "fix",
    mode = "fix",
)

# The following 4 platforms may be targeted explicitly from various execution platforms.
# See `rust-cc-toolchains.MODULE.bazel` for more information.

platform(
    name = "x86_64-linux-musl",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
        "@zig_sdk//libc:musl",
    ],
    visibility = [
        "//operator:__pkg__",
        "//runtime:__pkg__",
    ],
)

platform(
    name = "aarch64-linux-musl",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:linux",
        "@zig_sdk//libc:musl",
    ],
)

platform(
    name = "x86_64-macos",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:macos",
    ],
)

platform(
    name = "aarch64-macos",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:macos",
    ],
)

# Config setting indicating that the target platform is built against musl.
config_setting(
    name = "musl",
    constraint_values = ["@zig_sdk//libc:musl"],
    visibility = ["//visibility:public"],
)
