load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

package(
    default_visibility = [
        "//cluster:__subpackages__",
        "//operator/config/manager:__pkg__",
    ],
)

exports_files(["profiles.yaml"])

string_flag(
    name = "profile",
    build_setting_default = "",
    make_variable = "PROFILE",
)

py_binary(
    name = "load",
    srcs = ["load.py"],
    env = {"PROFILE": "$(PROFILE)"},
    toolchains = [":profile"],
    deps = [":loader"],
)

py_library(
    name = "loader",
    srcs = ["loader.py"],
    data = [":profiles.yaml"],
    deps = [
        "@pypi//pyyaml",
        "@rules_python//python/runfiles",
    ],
)

py_test(
    name = "validation-test",
    srcs = ["validation-test.py"],
    data = [
        ":profiles.yaml",
        ":schema.yaml",
    ],
    deps = [
        ":loader",
        "@pypi//jsonschema",
        "@pypi//pyyaml",
    ],
)
