# Vimana manages cluster variables using profiles.
# Each profile represents a cluster.
# Commands like `//cluster:create` and `//cluster:destroy` take the name of a profile,
# which must be defined here.
# This file must validate against the JSON schema in `schema.yaml`.
# Fake examples are provided here by default. Delete them.
#
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ NEVER COMMIT REAL PROFILES TO THE REPO ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
#
# Tell Git to ignore your local changes with:
#   git update-index --skip-worktree cluster/profile/profiles.yaml

gcp-example.com:
  state-store: "gs://google-storage-bucket/"
  zone: "us-east1-a"
  machine-type: "e2-medium"
  runtime-uri: "us-central1-docker.pkg.dev/project/repo/runtime:latest"
  operator-uri: "us-central1-docker.pkg.dev/project/repo/operator:latest"
  gcp:
    project: "project-id"
