"""Manage Vimana clusters."""

load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "create",
    srcs = ["create.py"],
    data = [
        ":vimanad-fetch.sh.tmpl",
        "//operator:deploy",
        "@rules_k8s//:cert-manager-helm-export",
        "@rules_k8s//:envoy-gateway-helm-export",
        "@rules_k8s//:helm",
        "@rules_k8s//:kops",
    ],
    env = {"PROFILE": "$(PROFILE)"},
    toolchains = ["//cluster/profile"],
    deps = [
        "//cluster/profile:loader",
        "//dev/lib:util-python",
        "@pypi//google_cloud_compute",
        "@pypi//kubernetes",
        "@pypi//rich",
    ],
)

py_binary(
    name = "destroy",
    srcs = ["destroy.py"],
    data = ["@rules_k8s//:kops"],
    env = {"PROFILE": "$(PROFILE)"},
    toolchains = ["//cluster/profile"],
    deps = [
        "//cluster/profile:loader",
        "//dev/lib:util-python",
        "@pypi//rich",
    ],
)
