load("@grpc//bazel:python_rules.bzl", "py_grpc_library", "py_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_wasm//rust:defs.bzl", "rust_component")
load("@rules_wasm//wasm:defs.bzl", "wit_package")

package(
    default_visibility = [
        "//e2e:__pkg__",
        "//runtime/tests:__pkg__",
    ],
)

wit_package(
    name = "adder-wit",
    srcs = ["adder.wit"],
    package = "foo:bar",
    deps = ["//compiler/wit:grpc"],
)

rust_component(
    name = "adder-rust",
    srcs = ["adder.rs"],
    wit = ":adder-wit",
    world = "adder-service",
)

# Compile text protobuf to binary protobuf.
genrule(
    name = "adder-metadata",
    srcs = ["adder.txtpb"],
    outs = ["adder.binpb"],
    cmd = "cat $(SRCS)" +
          " | ./$(location @protobuf//:protoc)" +
          " --encode=vimana.runtime.Metadata" +
          " --proto_path=`dirname $(location //runtime:metadata.proto)`" +
          " $(location //runtime:metadata.proto)" +
          " > $@",
    tools = [
        "//runtime:metadata.proto",
        "@protobuf//:protoc",
    ],
)

proto_library(
    name = "adder-proto",
    srcs = ["adder.proto"],
)

py_proto_library(
    name = "adder-py-pb2",
    deps = [":adder-proto"],
)

py_grpc_library(
    name = "adder-py-grpc",
    srcs = [":adder-proto"],
    deps = ["adder-py-pb2"],
)
