load("@bazel_skylib//rules:native_binary.bzl", "native_test")
load("@bazel_skylib//rules/directory:directory.bzl", "directory")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_python//python:defs.bzl", "py_library", "py_test")
load("@rules_rust//rust:defs.bzl", "rust_binary")
load("@rules_rust_prost//:defs.bzl", "rust_prost_library")
load("//compiler:defs.bzl", "vimana_protoc")
load(":dummy-service.bzl", "dummy_service")

package(default_testonly = True)

# For example usage of the conformance test runner, see:
# https://github.com/protocolbuffers/protobuf/blob/v33.1/conformance/bazel_conformance_test_runner.sh
native_test(
    name = "conformance-test",
    src = "@protobuf//conformance:conformance_test_runner",
    args = [
        "--enforce_recommended",
        "--failure_list",
        "$(location :conformance-known-failures.txt)",
        "$(location :conformance)",
    ],
    data = [
        ":conformance",
        ":conformance-known-failures.txt",
    ],
)

rust_binary(
    name = "conformance",
    srcs = ["conformance.rs"],
    data = [
        ":test-messages-proto2-vimana",
        ":test-messages-proto3-vimana",
    ],
    deps = [
        ":conformance-prost",
        "//runtime:metadata-prost",
        "//runtime:names",
        "//runtime/decode",
        "//runtime/encode",
        "@crates//:bytes",
        "@crates//:prost",
        "@crates//:tonic",
    ],
)

py_test(
    name = "success-test",
    srcs = ["success-test.py"],
    data = [":data"],
    deps = [":util"],
)

py_library(
    name = "util",
    srcs = ["util.py"],
    data = [
        "//compiler",
        "//runtime:metadata.proto",
        "@protobuf//:protoc",
    ],
)

directory(
    name = "data",
    srcs = glob(["data/**"]),
)

rust_prost_library(
    name = "conformance-prost",
    proto = "@protobuf//conformance:conformance_proto",
)

vimana_protoc(
    name = "test-messages-proto3-vimana",
    package = "protobuf_test_messages.proto3",
    proto = ":test-messages-proto3-proto",
)

proto_library(
    name = "test-messages-proto3-proto",
    srcs = [":test-messages-proto3-dummy-service"],
    deps = [
        "@protobuf//conformance/test_protos:test_messages_proto3_proto",
    ],
)

dummy_service(
    name = "test-messages-proto3-dummy-service",
    imports = ["google/protobuf/test_messages_proto3.proto"],
    package = "protobuf_test_messages.proto3",
    type = "TestAllTypesProto3",
)

vimana_protoc(
    name = "test-messages-proto2-vimana",
    ignore_unsupported_features = True,
    package = "protobuf_test_messages.proto2",
    proto = ":test-messages-proto2-proto",
)

proto_library(
    name = "test-messages-proto2-proto",
    srcs = [":test-messages-proto2-dummy-service"],
    deps = [
        "@protobuf//conformance/test_protos:test_messages_proto2_proto",
    ],
)

dummy_service(
    name = "test-messages-proto2-dummy-service",
    imports = ["google/protobuf/test_messages_proto2.proto"],
    package = "protobuf_test_messages.proto2",
    type = "TestAllTypesProto2",
)
