load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@environment//:environment.bzl", "localhost")
load("@rules_k8s//:resource.bzl", "kubectl_apply", "kubectl_delete")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_push")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("//dev/rules:platform-binary.bzl", "platform_binary")
load("//dev/rules:sh-in-place.bzl", "sh_in_place")

alias(
    name = "operator",
    actual = "//operator/cmd",
    visibility = ["//visibility:public"],
)

# Cross-compile the operator binary to package it in a container.
platform_binary(
    name = "operator-x86_64-linux",
    platform = "//dev:x86_64-linux-musl",
    target = ":operator",
)

default_image_name = "{}:5000/vimana-operator".format(localhost)

string_flag(
    name = "image-name",
    build_setting_default = default_image_name,
    make_variable = "IMAGE_NAME",
    visibility = ["//operator/config/manager:__pkg__"],
)

# Equivalent of `make docker-build` in a normal Operator SDK project.
oci_image(
    name = "image",
    base = "@distroless-static_linux_amd64",
    entrypoint = ":image-entrypoint",
    tars = [":image-tar"],
    user = "65532:65532",
    workdir = "/",
)

# Equivalent of `make docker-push` in a normal Operator SDK project.
oci_push(
    name = "image-push",
    image = ":image",
    remote_tags = ["latest"],
    repository = default_image_name,
    visibility = ["//dev/minikube:__pkg__"],
)

pkg_tar(
    name = "image-tar",
    srcs = [":operator-x86_64-linux"],
    remap_paths = {
        "/operator-x86_64-linux": "/manager",
    },
)

write_file(
    name = "image-entrypoint",
    out = "image-entrypoint.txt",
    content = ["/manager"],  # Operator SDK convention.
)

# Equivalent to `make install` in a normal Operator SDK project.
kubectl_apply(
    name = "install",
    srcs = [":install-resources"],
)

# Equivalent to `make uninstall` in a normal Operator SDK project.
kubectl_delete(
    name = "uninstall",
    srcs = [":install-resources"],
)

# Generate K8s resources for the CRDs.
# Partially equivalent to `make install` or `make uninstall` in a normal Operator SDK project
# (if combined with `kubectl apply` or `kubectl delete`).
genrule(
    name = "install-resources",
    srcs = ["//operator/config"],
    outs = ["install.yaml"],
    # The default load restrictor prevents loading symlinks that point outside the project root.
    # Since Bazel sandboxes use such symlinks, disable the load restrictor.
    cmd = "./$(location @rules_k8s//:kustomize) build" +
          " --load-restrictor=LoadRestrictionsNone" +
          " $(location //operator/config)/crd > \"$@\"",
    tools = ["@rules_k8s//:kustomize"],
)

# Equivalent to `make deploy` in a normal Operator SDK project.
kubectl_apply(
    name = "deploy",
    srcs = [":deploy-resources"],
    visibility = [
        "//cluster:__pkg__",
        "//dev/minikube:__pkg__",
    ],
)

# Equivalent to `make undeploy` in a normal Operator SDK project.
kubectl_delete(
    name = "undeploy",
    srcs = [":deploy-resources"],
)

# Generate K8s resources for the CRDS, RBAC policies, and the controller manager deployment.
# Partially equivalent to `make deploy` or `make undeploy` in a normal Operator SDK project
# (if combined with `kubectl apply` or `kubectl delete`).
genrule(
    name = "deploy-resources",
    srcs = ["//operator/config"],
    outs = ["deploy.yaml"],
    # The default load restrictor prevents loading symlinks that point outside the project root.
    # Since Bazel sandboxes use such symlinks, disable the load restrictor.
    cmd = "./$(location @rules_k8s//:kustomize) build" +
          " --load-restrictor=LoadRestrictionsNone" +
          " $(location //operator/config)/default > \"$@\"",
    tools = ["@rules_k8s//:kustomize"],
)

# Equivalent of `make generate manifests` in a normal Operator SDK project.
# Running this executable rule will mutate the source tree in-place!
sh_in_place(
    name = "generate",
    command = " && ".join([
        # Equivalent of `make generate`.
        " ".join([
            "\"$(location @rules_k8s//:controller-gen)\"",
            "object:headerFile='/dev/null'",
            "paths=\"./...\"",
        ]),
        # Equivalent of `make manifests`.
        " ".join([
            "\"$(location @rules_k8s//:controller-gen)\"",
            "rbac:roleName=manager-role",
            "crd",
            "webhook",
            "paths=\"./...\"",
            "output:crd:artifacts:config=config/crd/bases",
        ]),
    ]),
    data = ["@rules_k8s//:controller-gen"],
)
